### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by FlappyDude2003** [Dobby233Liu/MEMZPayloads#1]
Hey man, can i now build those .c files?

**Comment by Dobby233Liu** [comment]
Yes
Be sure to use GNU make and Mingw-w64 i686 gcc toolkit

**Comment by FlappyDude2003** [comment]
i know what gcc is but what is gnu make?

**Comment by Dobby233Liu** [comment]
Anyway, it's just `make`.

**Comment by FlappyDude2003** [comment]
so i just compile make?

**Comment by Dobby233Liu** [comment]
Yes

**Comment by Dobby233Liu** [comment]
Forget, also install python2

**Comment by FlappyDude2003** [comment]
i’m confused, explain in steps on how to compile a payload (sorry)

**Comment by Dobby233Liu** [comment]
sorry, this is wip. using make you can only build all of the payloads to <project_root>/Build/Bin

**Comment by Dobby233Liu** [comment]
But you can define the PL2 macro somewhere

**Comment by FlappyDude2003** [comment]
will they all be separate executables?

**Comment by Dobby233Liu** [comment]
Of course (but their size will be same, it's a desired effect)

**Comment by FlappyDude2003** [comment]
sooo what do i use to compile make?

**Comment by Dobby233Liu** [comment]
Compile the make program? There are many prebuilts for make

**Comment by FlappyDude2003** [comment]
noooo tell me the exact steps on how to compile the payloads. i’m not very good with this stuff (i’m sorry)

**Comment by Dobby233Liu** [comment]
Then just run `make` in the terminal

**Comment by FlappyDude2003** [comment]
can i use cygwin or what do i have to use to run it?

**Comment by Dobby233Liu** [comment]
yes, you can use cygwin or msys2

**Comment by FlappyDude2003** [comment]
i get an error on cygwin, its this "make2.sh: line 2: make: command not found" help?

**Comment by Dobby233Liu** [comment]
> i get an error on cygwin, its this "make2.sh: line 2: make: command not found" help?

I told you install make

**Comment by FlappyDude2003** [comment]
i realized that lol ill let you know if i get any more errors, i should install python too right?

**Comment by Dobby233Liu** [comment]
> i realized that lol ill let you know if i get any more errors, i should install python too right?

yes, install python2

**Comment by FlappyDude2003** [comment]
i got error 127, also got tons of: /bin/sh: line 2: gcc: command not found

**Comment by Dobby233Liu** [comment]
> i got error 127, also got tons of: /bin/sh: line 2: gcc: command not found

https://github.com/Dobby233Liu/MEMZPayloads/issues/1#issuecomment-497986642

**Comment by FlappyDude2003** [comment]
okay let me reinstall cygwin, name all the packages i need so i dont miss any.

**Comment by FlappyDude2003** [comment]
i reinstalled it with all the required packages and got tons of these errors: "gcc: error: unrecognized command line option ‘-municode’" and at the end i got error 1

**Comment by Dobby233Liu** [comment]
i messed it up. should not use cygwin, like the original memz

**Comment by FlappyDude2003** [comment]
what should i use instead?

**Comment by Dobby233Liu** [comment]
Directly install mingw-w64 and python2 on your Windows machine is a better choice.

**Comment by FlappyDude2003** [comment]
so should i install python from the official website and where do i get mingw? links?

**Comment by Dobby233Liu** [comment]
google it
(hint: on sourceforge)
https://sourceforge.net/projects/mingw-w64/

**Comment by FlappyDude2003** [comment]
i got python 3.7.3 and python launcher installed from the official website and i downloaded mingw and am installing it.

**Comment by Dobby233Liu** [comment]
no, python2

**Comment by FlappyDude2003** [comment]
so you want me to get an old version? and for mingw what threads do i use and what exception?

**Comment by Dobby233Liu** [comment]
yes, python2 (defined in the original memz). for mingw did quite recommend win32 version not posix.

**Comment by FlappyDude2003** [comment]
okay so i am using x86_x64 architecture, win32 threads, and seh as the exception. Is that correct? also im using choco to download python2 is that the correct way?

**Comment by Dobby233Liu** [comment]
both yes (but seem like original memz uses i686 arch, nvm)

**Comment by FlappyDude2003** [comment]
so do you recommend i use i686 or x86x64? or does it not really matter?

**Comment by Dobby233Liu** [comment]
no matter
edit: no

**Comment by FlappyDude2003** [comment]
alright, python 2 is finishing up installing and i will start mingw now.

**Comment by FlappyDude2003** [comment]
ok so everything is installed. what now?

**Comment by Dobby233Liu** [comment]
run make in the project dir

**Comment by FlappyDude2003** [comment]
so do i just type "make2.sh"?

**Comment by Dobby233Liu** [comment]
no, `make`. no make2 anymore, because its for debug

**Comment by FlappyDude2003** [comment]
so tell me the exact command i need to use. because cmd says "'make' is not recognized as an internal or external command,
operable program or batch file."

**Comment by Dobby233Liu** [comment]
> so tell me the exact command i need to use. because cmd says "'make' is not recognized as an internal or external command,
> operable program or batch file."

dl https://sourceforge.net/projects/gnuwin32/files/make/3.81/make-3.81.exe/download, then you can use make

**Comment by FlappyDude2003** [comment]
ok i downloaded make so what now

**Comment by Dobby233Liu** [comment]
https://github.com/Dobby233Liu/MEMZPayloads/issues/1#issuecomment-498001517

**Comment by FlappyDude2003** [comment]
yet again, error 1.
C:\Program Files (x86)\GnuWin32\bin>make
File not found - *.c
File not found - *.h
mkdir -p Build
mkdir -p Build/Bin
The syntax of the command is incorrect.
make: *** [Build/Bin] Error 1

**Comment by Dobby233Liu** [comment]
I added a alternative Makefile that fit cmd standards. pull out the new version and `make -C <the path of Makefile.Win32>`

**Comment by FlappyDude2003** [comment]
I got this:
C:\Program Files (x86)\GnuWin32\bin>make -C "C:\Program Files (x86)\GnuWin32\bin"
File not found - *.c
File not found - *.h
make: Entering directory `C:/Program Files (x86)/GnuWin32/bin'
mkdir -p Build
mkdir -p Build/Bin
The syntax of the command is incorrect.
make: *** [Build/Bin] Error 1
make: Leaving directory `C:/Program Files (x86)/GnuWin32/bin'

**Comment by Dobby233Liu** [comment]
ping @FlappyDude2003

**Comment by FlappyDude2003** [comment]
@Dobby233Liu still getting error 1? what does this mean?!
C:\Program Files (x86)\GnuWin32\bin>make -C "C:\Program Files (x86)\GnuWin32\bin"
File not found - *.c
File not found - *.h
make: Entering directory `C:/Program Files (x86)/GnuWin32/bin'
mkdir -p Build
mkdir -p Build/Bin
The syntax of the command is incorrect.
make: *** [Build/Bin] Error 1
make: Leaving directory `C:/Program Files (x86)/GnuWin32/bin'

**Comment by Dobby233Liu** [comment]
figured out yesterday: should use i686 arch of mingw
and `mklink -H <pythondir>\python2.exe <pythondir>\python.exe`
then pull the new version, use command on cmd:
```
make -C <the path of Makefile.Win32> clean
make -C <the path of Makefile.Win32>
```

**Comment by FlappyDude2003** [comment]
so type that mklink into cmd and reinstall mingw with win32 threads and i686 arch?

**Comment by FlappyDude2003** [comment]
more errors:
C:\Program Files (x86)\GnuWin32\bin>make -C "C:\Program Files (x86)\GnuWin32\bin\MEMZPayloads-master" clean
File not found - *.c
File not found - *.h
make: Entering directory `C:/Program Files (x86)/GnuWin32/bin/MEMZPayloads-master'
rm -r Build
process_begin: CreateProcess(NULL, rm -r Build, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2
make: Leaving directory `C:/Program Files (x86)/GnuWin32/bin/MEMZPayloads-master'

**Comment by Dobby233Liu** [comment]
so did u update the makefiles? https://github.com/Dobby233Liu/MEMZPayloads/commit/3a98e66d6017c73dad030e82b20705859301b693 fixes clean target

**Comment by FlappyDude2003** [comment]
how do i do that? because i changed that in the file and still get the same error.

**Comment by Dobby233Liu** [comment]
if you're using git to clone the repo then `git pull`
if you download by zip redownload one and unzip and replace all file in your local workspace
if you did a full update already, then did you use the customized makefile? this case is strange, i can run the makefile and straight to the exe build stage (but i cant go through it because i install a wrong ver of mingw)

**Comment by FlappyDude2003** [comment]
i did not redownload the whole thing yet, but i will try it later when i get home.

**Comment by FlappyDude2003** [comment]
okay i will try later when i get home. how come the makefile.win32 in the code isn’t updated yet?

**Comment by FlappyDude2003** [comment]
i got the updated version. how do i use the updated make file and not the other two?

**Comment by Dobby233Liu** [comment]
https://github.com/Dobby233Liu/MEMZPayloads/issues/1#issuecomment-498005245
It's Makefile*.Win32*

**Comment by FlappyDude2003** [comment]
so i type “make -C <directory>\Makefile*.Win32*”?

**Comment by FlappyDude2003** [comment]
is there any other way we can contact each other? like some kind of DM or skype instead of using comments?

**Comment by Dobby233Liu** [comment]
no

**Comment by Dobby233Liu** [comment]
i dont have these stuff

**Comment by Dobby233Liu** [comment]
and type `make -C Makefile.Win32 clean && make -C Makefile.Win32`

**Comment by FlappyDude2003** [comment]
I get this error:
C:\Program Files (x86)\GnuWin32\bin>make -C Makefile.Win32 clean && make -C Makefile.Win32
make: *** Makefile.Win32: Invalid argument.  Stop.

Can you just do this on your computer and send me the executables in a zip?

**Comment by Dobby233Liu** [comment]
sorry, no bin for various reasons.
```
make -C Makefile.Win32 clean
make -C Makefile.Win32
```

**Comment by FlappyDude2003** [comment]
Error:
C:\Program Files (x86)\GnuWin32\bin>make -C Makefile.Win32
make: *** Makefile.Win32: Invalid argument.  Stop.

**Comment by FlappyDude2003** [comment]
So it turns out i had to replace the forward slashes in the makefile and use make -f and not make -C
But i still get an error:
mkdir Build
mkdir Build\Bin
python2 Data\genData.py Build\Data.c Build\Data.h
echo #define DESTRUCTIVE > Build\Mode.h
for /F "delims= " %%n in ('echo 0 1 2 3 4 5 6 7 8 9 10') do gcc -nostdlib -nodefaultlibs -std=c99 -Wl,-e_start -s -mwindows -m32 -municode -Os -w -march=i486  Build\Data.c -luser32 -lkernel32 -lgdi32 -lwinmm -lcomctl32 -ladvapi32 -lshell32 -lpsapi -o Build\Bin\MEMZPayloads-%%n.exe -DPL2=%%n
gcc: error: unrecognized command line option '-municode'
make: *** [destructive-exe] Error 1

**Comment by FlappyDude2003** [comment]
what is that? how do i do it?

**Comment by Dobby233Liu** [comment]
i just changed something

**Comment by FlappyDude2003** [comment]
so can i just redownload the zip?

**Comment by Dobby233Liu** [comment]
can you run `i686-w64-mingw32-gcc -v`?

**Comment by FlappyDude2003** [comment]
I get this:
C:\WINDOWS\system32>i686-w64-mingw32-gcc -v
'i686-w64-mingw32-gcc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Dobby233Liu** [comment]
so you need reinstall mingw-w64 with i686 arch win32 thread

**Comment by Dobby233Liu** [comment]
stale close
